# Generated by Django 4.2.4 on 2023-11-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'Variant', 'verbose_name_plural': 'Variants'},
        ),
        migrations.RemoveField(
            model_name='variant',
            name='variant_name',
        ),
        migrations.AddField(
            model_name='variant',
            name='body_type',
            field=models.CharField(blank=True, choices=[('resin', 'Resin'), ('metal', 'Metal')], max_length=50),
        ),
        migrations.AddField(
            model_name='variant',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='variant',
            name='strap_type',
            field=models.CharField(blank=True, choices=[('chain', 'Chain'), ('leather', 'Leather'), ('resin', 'Resin')], max_length=50),
        ),
    ]
