# Generated by Django 4.2.4 on 2023-11-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_variant_options_remove_variant_variant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='stocks',
            field=models.IntegerField(default=0),
        ),
    ]
