# Generated by Django 4.2.4 on 2023-11-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_variant_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
    ]
