# Generated by Django 4.2.4 on 2023-11-15 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_remove_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='category.product'),
        ),
    ]
