# Generated by Django 4.2.4 on 2023-11-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_variant_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_stocks',
        ),
    ]
