# Generated by Django 4.2.4 on 2023-11-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_remove_product_total_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='stocks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
