# Generated by Django 4.2.4 on 2023-11-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_offer_category_offers_product_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
    ]
