# Generated by Django 4.2.4 on 2023-12-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_remove_offer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
