# Generated by Django 4.2.4 on 2023-12-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0017_remove_product_real_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='checkprice',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
