# Generated by Django 4.2.4 on 2023-12-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0018_product_checkprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dis_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
