# Generated by Django 4.2.4 on 2023-12-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0019_product_dis_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='temp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
