# Generated by Django 4.2.4 on 2023-12-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0020_product_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='temp',
        ),
        migrations.AddField(
            model_name='offer',
            name='temp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
