# Generated by Django 4.2.4 on 2023-12-01 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0021_remove_product_temp_offer_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='temp',
        ),
    ]
