# Generated by Django 4.2.4 on 2023-11-28 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_alter_product_price'),
        ('cart', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='variations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.variant'),
        ),
    ]
