# Generated by Django 4.2.4 on 2023-11-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_wallet_wallet_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=255, unique=True)),
                ('minimum_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coupon_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
