# Generated by Django 4.2.4 on 2023-11-29 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 11, 28, 4, 48, 33, 482338, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_usage_count',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
