# Generated by Django 4.2.4 on 2023-11-29 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_coupon_expiry_date_coupon_max_usage_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 11, 28, 8, 21, 56, 163652, tzinfo=datetime.timezone.utc)),
        ),
    ]
