# Generated by Django 4.2.4 on 2023-11-29 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_coupon_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 11, 28, 9, 27, 43, 24744, tzinfo=datetime.timezone.utc)),
        ),
    ]
