# Generated by Django 4.2.4 on 2023-12-01 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_redeemed_coupon_is_redeemed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='max_usage_count',
        ),
        migrations.RemoveField(
            model_name='redeemed_coupon',
            name='dummy_count',
        ),
        migrations.RemoveField(
            model_name='redeemed_coupon',
            name='real_count',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 11, 30, 4, 3, 45, 660394, tzinfo=datetime.timezone.utc)),
        ),
    ]
