# Generated by Django 4.2.6 on 2023-12-09 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_alter_coupon_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 12, 8, 14, 3, 7, 676955, tzinfo=datetime.timezone.utc)),
        ),
    ]
