# Generated by Django 4.2.6 on 2023-12-10 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_alter_coupon_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 12, 9, 5, 31, 58, 30285, tzinfo=datetime.timezone.utc)),
        ),
    ]
